### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name":"Vinay",
    "email": "vinay@bingi",
    "password":"123456"
}


### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "vinay@bingi",
  "password": "123456"
}

### Get Profile
GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTIxMTJhNGIzOWFmODAzZjUxOGU1YiIsImlhdCI6MTc3NjQzNjczNiwiZXhwIjoxNzc3MDQxNTM2fQ.w8F4iDSpmAsP_HRSPs3qdSYYLGQkpvfX4HzamFB_790


### Create Post
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTI3MjA3Nzc2YTY2NTdmNTg0YWZiYSIsImlhdCI6MTc3NjQ0ODAyMiwiZXhwIjoxNzc3MDUyODIyfQ.A1ooBLZslf2wEjw_GVryRE2p1BRQCZ8n4n9wT-nUhAI

{
    "title":"Learn React",
    "description":"I want to learn React",
    "skillOffered":"React",
    "skillWanted":"Python"
}

### get all posts
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTIxMTJhNGIzOWFmODAzZjUxOGU1YiIsImlhdCI6MTc3NjQzNjczNiwiZXhwIjoxNzc3MDQxNTM2fQ.w8F4iDSpmAsP_HRSPs3qdSYYLGQkpvfX4HzamFB_790

### get my posts
GET http://localhost:5000/api/posts/mine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTI3MjA3Nzc2YTY2NTdmNTg0YWZiYSIsImlhdCI6MTc3NjQ0ODAyMiwiZXhwIjoxNzc3MDUyODIyfQ.A1ooBLZslf2wEjw_GVryRE2p1BRQCZ8n4n9wT-nUhAI

### update post
PUT http://localhost:5000/api/posts/69e27237776a6657f584afbb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTI3MjA3Nzc2YTY2NTdmNTg0YWZiYSIsImlhdCI6MTc3NjQ0ODAyMiwiZXhwIjoxNzc3MDUyODIyfQ.A1ooBLZslf2wEjw_GVryRE2p1BRQCZ8n4n9wT-nUhAI

{
    "title":"Learn React",
    "description":"I want to learn React",
    "skillOffered":"React",
    "skillWanted":"Python"
}

### delete post
DELETE http://localhost:5000/api/posts/69e27237776a6657f584afbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTI3MjA3Nzc2YTY2NTdmNTg0YWZiYSIsImlhdCI6MTc3NjQ0ODAyMiwiZXhwIjoxNzc3MDUyODIyfQ.A1ooBLZslf2wEjw_GVryRE2p1BRQCZ8n4n9wT-nUhAI